### ISSUE TITLE
Search not working on Quran.com

### ISSUE THREAD

**Issue by codedrunk** [quran/quran.com-api#187]
AoA.
Looks like the search on Quran.com has been broken for some time. Sorry if this is the wrong place to report it but I sent an error report on Zekdesk as well as support, but I received no reply. I'm using Chrome Version 67.0.3396.62 on Windows 10 x64. Here's the request cURL:

`curl "https://quran.com/api/api/v3/search?q=qadr^&language=en" -H "dnt: 1" -H "accept-encoding: gzip, deflate, br" -H "accept-language: en-US,en;q=0.9" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36" -H "accept: */*" -H "referer: https://quran.com/search?q=qadr" -H "authority: quran.com" -H "cookie: currentLocale=en; options=^%^7B^%^7D; _ga=GA1.2.14959037.1528388711; _gid=GA1.2.2015075783.1528388711; _gat=1; mp_d3f9b2f15c4bf0509e85845b56921034_mixpanel=^%^7B^%^22distinct_id^%^22^%^3A^%^20^%^22163db10f2c9a1-048a5ab7783715-47e1f32-1fa400-163db10f2cb329^%^22^%^2C^%^22^%^24initial_referrer^%^22^%^3A^%^20^%^22^%^24direct^%^22^%^2C^%^22^%^24initial_referring_domain^%^22^%^3A^%^20^%^22^%^24direct^%^22^%^7D" --compressed`

Here's the response:

```
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

```

Error appears at raven.js:951

**Comment by ahmedre** [comment]
wa3laikum alsalam,
looks like search was down on one of the boxes. it should work now.
walsalam 3alaikum.

**Comment by codedrunk** [comment]
I was about to comment here that the issue is back. I just couldn't find the repo.

**Comment by ahmedre** [comment]
fixed again.

**Comment by codedrunk** [comment]
AA bro. It's broken again, with the same error.

**Comment by ahmedre** [comment]
Fixed - we are working on fixing this so that it stops dying like this in sha’ Allah
