### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by haroonfida** [quran/quran.com-api#335]
Salam,
![Untitled](https://user-images.githubusercontent.com/33434926/116003184-42be2a80-a5fd-11eb-9d6d-9612d7f86305.png)

I wish you the best of health. I just saw that the English translation of Surah Qaf (https://quran.com/50) by Muhammad Hijab has been wrongly associated with the Arabic verses. Please make the correction. JazakALLAH. Salam.

Kind regards,
Syed Haroon Fida.

**Comment by benomaire** [comment]
Thank you for the report!
@naveed-ahmad can you pull the new version? this was fixed on quranenc some weeks ago

**Comment by naveed-ahmad** [comment]
Synced again, closing this.
http://beta.quran.com/50?translations=207

**Comment by haroonfida** [comment]
Salam,

Its still the same 
https://quran.com/50
Check the translation by Muhammad Hijab

Kind regards,
Haroon.

**Comment by haroonfida** [comment]
> Synced again, closing this.
> http://beta.quran.com/50?translations=207

Salam,

Its still the same
https://quran.com/50
Check the translation by Muhammad Hijab

Kind regards,
Haroon.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
note the link - beta.quran.com - it's on the beta site but not deployed to quran.com yet.
we will deploy it with several other fixes when ready in sha' Allah, but in the meanwhile, you can use the beta site.
walsalam 3alaikum.

**Comment by haroonfida** [comment]
got it 
JAZAKALLAH
